ALTER TABLE shoop_customertaxgroup RENAME TO E-Commerce_customertaxgroup;
ALTER TABLE shoop_manufacturer RENAME TO E-Commerce_manufacturer;
ALTER TABLE shoop_producttype RENAME TO E-Commerce_producttype;
ALTER TABLE shoop_producttype_attributes RENAME TO E-Commerce_producttype_attributes;
ALTER TABLE shoop_salesunit RENAME TO E-Commerce_salesunit;
ALTER TABLE shoop_shopproduct_categories RENAME TO E-Commerce_shopproduct_categories;
ALTER TABLE shoop_shopproduct_payment_methods RENAME TO E-Commerce_shopproduct_payment_methods;
ALTER TABLE shoop_shopproduct_shipping_methods RENAME TO E-Commerce_shopproduct_shipping_methods;
ALTER TABLE shoop_taxclass RENAME TO E-Commerce_taxclass;
ALTER TABLE shoop_shopproduct_visibility_groups RENAME TO E-Commerce_shopproduct_visibility_groups;
ALTER TABLE shoop_contactgroup_members RENAME TO E-Commerce_contactgroup_members;
ALTER TABLE shoop_category_visibility_groups RENAME TO E-Commerce_category_visibility_groups;
ALTER TABLE shoop_taxclass_translation RENAME TO E-Commerce_taxclass_translation;
ALTER TABLE shoop_productvariationvariablevalue_translation RENAME TO E-Commerce_productvariationvariablevalue_translation;
ALTER TABLE shoop_productvariationvariable_translation RENAME TO E-Commerce_productvariationvariable_translation;
ALTER TABLE shoop_producttype_translation RENAME TO E-Commerce_producttype_translation;
ALTER TABLE shoop_product_translation RENAME TO E-Commerce_product_translation;
ALTER TABLE shoop_productmedia_translation RENAME TO E-Commerce_productmedia_translation;
ALTER TABLE shoop_customertaxgroup_translation RENAME TO E-Commerce_customertaxgroup_translation;
ALTER TABLE shoop_contactgroup_translation RENAME TO E-Commerce_contactgroup_translation;
ALTER TABLE shoop_category_translation RENAME TO E-Commerce_category_translation;
ALTER TABLE shoop_orderlinetax RENAME TO E-Commerce_orderlinetax;
ALTER TABLE shoop_tax RENAME TO E-Commerce_tax;
ALTER TABLE shoop_tax_translation RENAME TO E-Commerce_tax_translation;
ALTER TABLE shoop_category RENAME TO E-Commerce_category;
ALTER TABLE shoop_attribute RENAME TO E-Commerce_attribute;
ALTER TABLE shoop_attribute_translation RENAME TO E-Commerce_attribute_translation;
ALTER TABLE shoop_category_shops RENAME TO E-Commerce_category_shops;
ALTER TABLE shoop_categorylogentry RENAME TO E-Commerce_categorylogentry;
ALTER TABLE shoop_companycontact_members RENAME TO E-Commerce_companycontact_members;
ALTER TABLE shoop_companycontact RENAME TO E-Commerce_companycontact;
ALTER TABLE shoop_configurationitem RENAME TO E-Commerce_configurationitem;
ALTER TABLE shoop_counter RENAME TO E-Commerce_counter;
ALTER TABLE shoop_immutableaddress RENAME TO E-Commerce_immutableaddress;
ALTER TABLE shoop_mutableaddress RENAME TO E-Commerce_mutableaddress;
ALTER TABLE shoop_orderline RENAME TO E-Commerce_orderline;
ALTER TABLE shoop_orderlogentry RENAME TO E-Commerce_orderlogentry;
ALTER TABLE shoop_orderstatus RENAME TO E-Commerce_orderstatus;
ALTER TABLE shoop_orderstatus_translation RENAME TO E-Commerce_orderstatus_translation;
ALTER TABLE shoop_payment RENAME TO E-Commerce_payment;
ALTER TABLE shoop_persistentcacheentry RENAME TO E-Commerce_persistentcacheentry;
ALTER TABLE shoop_product RENAME TO E-Commerce_product;
ALTER TABLE shoop_productattribute RENAME TO E-Commerce_productattribute;
ALTER TABLE shoop_productattribute_translation RENAME TO E-Commerce_productattribute_translation;
ALTER TABLE shoop_productcrosssell RENAME TO E-Commerce_productcrosssell;
ALTER TABLE shoop_productlogentry RENAME TO E-Commerce_productlogentry;
ALTER TABLE shoop_productmedia RENAME TO E-Commerce_productmedia;
ALTER TABLE shoop_productmedia_shops RENAME TO E-Commerce_productmedia_shops;
ALTER TABLE shoop_productpackagelink RENAME TO E-Commerce_productpackagelink;
ALTER TABLE shoop_productvariationresult RENAME TO E-Commerce_productvariationresult;
ALTER TABLE shoop_productvariationvariable RENAME TO E-Commerce_productvariationvariable;
ALTER TABLE shoop_productvariationvariablevalue RENAME TO E-Commerce_productvariationvariablevalue;
ALTER TABLE shoop_salesunit_translation RENAME TO E-Commerce_salesunit_translation;
ALTER TABLE shoop_savedaddress RENAME TO E-Commerce_savedaddress;
ALTER TABLE shoop_shipmentproduct RENAME TO E-Commerce_shipmentproduct;
ALTER TABLE shoop_shopproduct_suppliers RENAME TO E-Commerce_shopproduct_suppliers;
ALTER TABLE shoop_shop_translation RENAME TO E-Commerce_shop_translation;
ALTER TABLE shoop_suppliedproduct RENAME TO E-Commerce_suppliedproduct;
ALTER TABLE shoop_supplier RENAME TO E-Commerce_supplier;
ALTER TABLE shoop_front_storedbasket_products RENAME TO E-Commerce_front_storedbasket_products;
ALTER TABLE shoop_front_storedbasket RENAME TO E-Commerce_front_storedbasket;
ALTER TABLE shoop_notify_notification RENAME TO E-Commerce_notify_notification;
ALTER TABLE shoop_notify_script RENAME TO E-Commerce_notify_script;
ALTER TABLE shoop_simple_cms_page_translation RENAME TO E-Commerce_simple_cms_page_translation;
ALTER TABLE shoop_xtheme_savedviewconfig RENAME TO E-Commerce_xtheme_savedviewconfig;
ALTER TABLE shoop_xtheme_themesettings RENAME TO E-Commerce_xtheme_themesettings;
ALTER TABLE shoop_shopproduct RENAME TO E-Commerce_shopproduct;
ALTER TABLE shoop_shop RENAME TO E-Commerce_shop;
ALTER TABLE shoop_customer_group_pricing_cgpprice RENAME TO E-Commerce_customer_group_pricing_cgpprice;
ALTER TABLE shoop_contactgroup RENAME TO E-Commerce_contactgroup;
ALTER TABLE shoop_simple_cms_page RENAME TO E-Commerce_simple_cms_page;
ALTER TABLE shoop_personcontact RENAME TO E-Commerce_personcontact;
ALTER TABLE shoop_paymentmethod_translation RENAME TO E-Commerce_paymentmethod_translation;
ALTER TABLE shoop_shippingmethod_translation RENAME TO E-Commerce_shippingmethod_translation;
ALTER TABLE shoop_carrier RENAME TO E-Commerce_carrier;
ALTER TABLE shoop_fixedcostbehaviorcomponent RENAME TO E-Commerce_fixedcostbehaviorcomponent;
ALTER TABLE shoop_paymentprocessor RENAME TO E-Commerce_paymentprocessor;
ALTER TABLE shoop_waivingcostbehaviorcomponent RENAME TO E-Commerce_waivingcostbehaviorcomponent;
ALTER TABLE shoop_weightlimitsbehaviorcomponent RENAME TO E-Commerce_weightlimitsbehaviorcomponent;
ALTER TABLE shoop_serviceprovider RENAME TO E-Commerce_serviceprovider;
ALTER TABLE shoop_servicebehaviorcomponent RENAME TO E-Commerce_servicebehaviorcomponent;
ALTER TABLE shoop_paymentmethod_behavior_components RENAME TO E-Commerce_paymentmethod_behavior_components;
ALTER TABLE shoop_shippingmethod_behavior_components RENAME TO E-Commerce_shippingmethod_behavior_components;
ALTER TABLE shoop_customcarrier RENAME TO E-Commerce_customcarrier;
ALTER TABLE shoop_custompaymentprocessor RENAME TO E-Commerce_custompaymentprocessor;
ALTER TABLE shoop_serviceprovider_translation RENAME TO E-Commerce_serviceprovider_translation;
ALTER TABLE shoop_waivingcostbehaviorcomponent_translation RENAME TO E-Commerce_waivingcostbehaviorcomponent_translation;
ALTER TABLE shoop_fixedcostbehaviorcomponent_translation RENAME TO E-Commerce_fixedcostbehaviorcomponent_translation;
ALTER TABLE shoop_paymentmethod RENAME TO E-Commerce_paymentmethod;
ALTER TABLE shoop_shippingmethod RENAME TO E-Commerce_shippingmethod;
ALTER TABLE shoop_weightbasedpricingbehaviorcomponent RENAME TO E-Commerce_weightbasedpricingbehaviorcomponent;
ALTER TABLE shoop_weightbasedpricerange RENAME TO E-Commerce_weightbasedpricerange;
ALTER TABLE shoop_weightbasedpricerange_translation RENAME TO E-Commerce_weightbasedpricerange_translation;
ALTER TABLE shoop_shipment RENAME TO E-Commerce_shipment;
ALTER TABLE shoop_contact RENAME TO E-Commerce_contact;
ALTER TABLE shoop_groupavailabilitybehaviorcomponent RENAME TO E-Commerce_groupavailabilitybehaviorcomponent;
ALTER TABLE shoop_groupavailabilitybehaviorcomponent_groups RENAME TO E-Commerce_groupavailabilitybehaviorcomponent_groups;
ALTER TABLE shoop_roundingbehaviorcomponent RENAME TO E-Commerce_roundingbehaviorcomponent;
ALTER TABLE shoop_order RENAME TO E-Commerce_order;
ALTER TABLE shoop_staffonlybehaviorcomponent RENAME TO E-Commerce_staffonlybehaviorcomponent;
ALTER TABLE shoop_testing_expensiveswedenbehaviorcomponent RENAME TO E-Commerce_testing_expensiveswedenbehaviorcomponent;
ALTER TABLE shoop_testing_paymentwithcheckoutphase RENAME TO E-Commerce_testing_paymentwithcheckoutphase;
ALTER TABLE shoop_testing_pseudopaymentprocessor RENAME TO E-Commerce_testing_pseudopaymentprocessor;
ALTER TABLE shoop_testing_carrierwithcheckoutphase RENAME TO E-Commerce_testing_carrierwithcheckoutphase;
DELETE FROM django_migrations WHERE app='shoop_addons' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_addons' WHERE app='shoop_addons';
DELETE FROM django_migrations WHERE app='shoop_admin' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_admin' WHERE app='shoop_admin';
DELETE FROM django_migrations WHERE app='shoop_api' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_api' WHERE app='shoop_api';
DELETE FROM django_migrations WHERE app='shoop' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce' WHERE app='shoop';
DELETE FROM django_migrations WHERE app='shoop_customer_group_pricing' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_customer_group_pricing' WHERE app='shoop_customer_group_pricing';
DELETE FROM django_migrations WHERE app='default_tax' AND name != '0001_initial';
UPDATE django_migrations SET app='default_tax' WHERE app='default_tax';
DELETE FROM django_migrations WHERE app='shoop_front' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front' WHERE app='shoop_front';
DELETE FROM django_migrations WHERE app='shoop_front.auth' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.auth' WHERE app='shoop_front.auth';
DELETE FROM django_migrations WHERE app='shoop_front.customer_information' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.customer_information' WHERE app='shoop_front.customer_information';
DELETE FROM django_migrations WHERE app='shoop_front.personal_order_history' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.personal_order_history' WHERE app='shoop_front.personal_order_history';
DELETE FROM django_migrations WHERE app='shoop_front.registration' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.registration' WHERE app='shoop_front.registration';
DELETE FROM django_migrations WHERE app='shoop_front.simple_order_notification' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.simple_order_notification' WHERE app='shoop_front.simple_order_notification';
DELETE FROM django_migrations WHERE app='shoop_front.simple_search' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_front.simple_search' WHERE app='shoop_front.simple_search';
DELETE FROM django_migrations WHERE app='shoop_notify' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_notify' WHERE app='shoop_notify';
DELETE FROM django_migrations WHERE app='shoop_order_printouts' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_order_printouts' WHERE app='shoop_order_printouts';
DELETE FROM django_migrations WHERE app='shoop_simple_cms' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_simple_cms' WHERE app='shoop_simple_cms';
DELETE FROM django_migrations WHERE app='simple_supplier' AND name != '0001_initial';
UPDATE django_migrations SET app='simple_supplier' WHERE app='simple_supplier';
DELETE FROM django_migrations WHERE app='shoop_testing' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_testing' WHERE app='shoop_testing';
DELETE FROM django_migrations WHERE app='shoop.themes.classic_gray' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce.themes.classic_gray' WHERE app='shoop.themes.classic_gray';
DELETE FROM django_migrations WHERE app='shoop_utils' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_utils' WHERE app='shoop_utils';
DELETE FROM django_migrations WHERE app='shoop_xtheme' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_xtheme' WHERE app='shoop_xtheme';
DELETE FROM django_migrations WHERE app='shoop_tests_core' AND name != '0001_initial';
UPDATE django_migrations SET app='E-Commerce_tests_core' WHERE app='shoop_tests_core';
UPDATE django_content_type SET app_label='E-Commerce_addons' WHERE app_label='shoop_addons';
UPDATE django_content_type SET app_label='E-Commerce_admin' WHERE app_label='shoop_admin';
UPDATE django_content_type SET app_label='E-Commerce_api' WHERE app_label='shoop_api';
UPDATE django_content_type SET app_label='E-Commerce' WHERE app_label='shoop';
UPDATE django_content_type SET app_label='E-Commerce_customer_group_pricing' WHERE app_label='shoop_customer_group_pricing';
UPDATE django_content_type SET app_label='default_tax' WHERE app_label='default_tax';
UPDATE django_content_type SET app_label='E-Commerce_front' WHERE app_label='shoop_front';
UPDATE django_content_type SET app_label='E-Commerce_front.auth' WHERE app_label='shoop_front.auth';
UPDATE django_content_type SET app_label='E-Commerce_front.customer_information' WHERE app_label='shoop_front.customer_information';
UPDATE django_content_type SET app_label='E-Commerce_front.personal_order_history' WHERE app_label='shoop_front.personal_order_history';
UPDATE django_content_type SET app_label='E-Commerce_front.registration' WHERE app_label='shoop_front.registration';
UPDATE django_content_type SET app_label='E-Commerce_front.simple_order_notification' WHERE app_label='shoop_front.simple_order_notification';
UPDATE django_content_type SET app_label='E-Commerce_front.simple_search' WHERE app_label='shoop_front.simple_search';
UPDATE django_content_type SET app_label='E-Commerce_notify' WHERE app_label='shoop_notify';
UPDATE django_content_type SET app_label='E-Commerce_order_printouts' WHERE app_label='shoop_order_printouts';
UPDATE django_content_type SET app_label='E-Commerce_simple_cms' WHERE app_label='shoop_simple_cms';
UPDATE django_content_type SET app_label='simple_supplier' WHERE app_label='simple_supplier';
UPDATE django_content_type SET app_label='E-Commerce_testing' WHERE app_label='shoop_testing';
UPDATE django_content_type SET app_label='E-Commerce.themes.classic_gray' WHERE app_label='shoop.themes.classic_gray';
UPDATE django_content_type SET app_label='E-Commerce_utils' WHERE app_label='shoop_utils';
UPDATE django_content_type SET app_label='E-Commerce_xtheme' WHERE app_label='shoop_xtheme';
UPDATE django_content_type SET app_label='E-Commerce_tests_core' WHERE app_label='shoop_tests_core';
